language: python

python:
    - "3.6"

cache: pip

install:
  - "pip install -r .travis/requirements.txt"

branches:
  only:
    - master

before_script:
  - ./.travis/git_branch_linter.sh

script:
  - ./.travis/integration_assurances.sh

