# -*- coding: utf-8 -*-
"""

    Problem #2 - Even Fibonacci numbers
    -----------------------------------

    Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms will be::

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.
"""

# used by fib(), can get rather huge....
fibs = {0: 0, 1: 1}


def fib(n):
    """ Return n-th fibonacci number using a method developed
    by E. W. Dijkstra

    Copied from:
        http://en.literateprograms.org/Fibonacci_numbers_(Python)
    """

    if n in fibs:
        return fibs[n]
    if n % 2 == 0:
        fibs[n] = ((2 * fib((n / 2) - 1)) + fib(n / 2)) * fib(n / 2)
        return fibs[n]
    fibs[n] = (fib((n - 1) / 2) ** 2) + (fib((n+1) / 2) ** 2)
    return fibs[n]


def fib_generator():
    """ Creates a generator which will return the next Fibonacci number """

    counter = 0
    while True:
        yield fib(counter)
        counter += 1


def problem():
    """ Attempt to solve the problem... """

    print 'problem #2'
    upper_bound = 4 * 10**6
    gen = fib_generator()
    total = 0
    while True:
        num = gen.next()
        if num >= upper_bound:
            break
        #: only even
        if num % 2 == 0:
            total += num
    print 'sum of even fibonacci numbers less than 4e6 is: %d ' % total

if __name__ == "__main__":

    problem()
