# -*- coding: utf-8 -*-
"""

    Problem #45 - Triangular, pentagonal, and hexagonal
    ---------------------------------------------------

    Triangle, pentagonal, and hexagonal numbers are generated by the following
    formulae:

    Triangle        T(n) = n(n+1)/2     1, 3, 6, 10, 15, ...

    Pentagonal      P(n) = n(3n−1)/2    1, 5, 12, 22, 35, ...

    Hexagonal       H(n) = n(2n−1)      1, 6, 15, 28, 45, ...

    It can be verified that T(285) = P(165) = H(143) = 40755.

    Find the next triangle number that is also pentagonal and hexagonal.

"""

t = lambda x: x*(x+1)/2
p = lambda x: x*(3*x-1)/2
h = lambda x: x*(2*x-1)


def problem():
    """ Attempt to solve the problem... """

    print 'problem #45'
    t_0 = 286
    p_0 = 166
    h_0 = 144
    triangle_number = 40755

    for x in xrange(100000):

        inc = 100000
        l1 = set(t(x) for x in xrange(t_0, inc+1))
        l2 = set(p(x) for x in xrange(p_0, inc+1))
        l3 = set(h(x) for x in xrange(h_0, inc+1))

        if l1.intersection(l2).intersection(l3):
            triangle_number = l1.intersection(l2).intersection(l3)
            break
        t_0 += inc
        p_0 += inc
        h_0 += inc

    print 'next triangle number is %d' % triangle_number.pop()

if __name__ == "__main__":

    problem()
