# -*- coding: utf-8 -*-
"""

    Problem #44 - Pentagon numbers
    ------------------------------

    Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first
    ten pentagonal numbers are:

        1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

    It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
    70 − 22 = 48, is not pentagonal.

    Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
    difference are pentagonal and D = |Pk − Pj| is minimised; what is the
    value of D?

"""


def problem_44():
    """ Attempt to solve the problem... """

    numbers = {x * (3 * x - 1) / 2: True for x in xrange(1, 10000)}
    for num1 in numbers.keys():
        for num2 in numbers.keys():
            if numbers.get(num1 + num2) and numbers.get(num2 - num1):
                return num2 - num1


if __name__ == "__main__":

    print 'problem #44'
    ANSWER = problem_44()
    print 'The distance between two pentagonal numbers is %s' % ANSWER
